version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - cd ExpenseSplit
      - dotnet clean
      - dotnet publish -c Release -o output
  post_build:
    commands:
      - aws s3 rm s3://expensesplit-frontend --recursive
      - aws s3 cp output/wwwroot/ s3://expensesplit-frontend --recursive
artifacts:
  files:
    - '**/*'
  base-directory: ExpenseSplit/output/wwwroot